int a := 1;
int b, c := 3;
int d[4000];

char e := 'g';
char f, g := 'g';
char h[4000];
char z[20];

boolean i := TRUE;
boolean j, k:= FALSE;
boolean l[2000];

main {
    /*
    i := a + y;
    */
    readln(x);
}



/* doigenes aqui ->
 utlio aqui ->
 acrlin nao aqui -> 
int int
int[] int
int int[]
int[] int[]

char char
char[] char
char char[]
char[] char[]

bool bool
bool[] bool
bool bool[]
bool[] bool[] */